#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────
#  MailGo Install Script
#  Generates .env, starts Docker containers, prints initial password.
# ─────────────────────────────────────────────────────────────────

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${CYAN}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ok]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
die()   { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

# ── Check prerequisites ─────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "Docker is not installed. https://docs.docker.com/get-docker/"

if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  die "Docker Compose is not installed. https://docs.docker.com/compose/install/"
fi

# ── Generate .env ────────────────────────────────────────────────
if [ -f .env ]; then
  warn ".env already exists — skipping generation."
  warn "Delete it first if you want to regenerate."
else
  info "Generating .env ..."

  ENC_KEY=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n')
  MYSQL_ROOT_PW=$(openssl rand -base64 18 2>/dev/null || head -c 18 /dev/urandom | base64 | head -c 24)
  MYSQL_PW=$(openssl rand -base64 18 2>/dev/null || head -c 18 /dev/urandom | base64 | head -c 24)

  cat > .env <<EOF
# Auto-generated by install.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

ENCRYPTION_KEY=${ENC_KEY}
SERVER_PORT=8080

MYSQL_USER=mailgo
MYSQL_PASSWORD=${MYSQL_PW}
MYSQL_HOST=mysql
MYSQL_PORT=3306
MYSQL_DATABASE=mailgo
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_DB=0
EOF

  ok ".env created."
fi

# ── Start containers ─────────────────────────────────────────────
info "Starting MailGo ..."
$COMPOSE up -d --build

# ── Wait for services ────────────────────────────────────────────
info "Waiting for services to be ready ..."
for i in $(seq 1 90); do
  if docker inspect --format='{{.State.Health.Status}}' mailgo 2>/dev/null | grep -q "healthy\|running"; then
    break
  fi
  sleep 2
done

# ── Print initial password ───────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                      MailGo is ready!                            ║"
echo "╠══════════════════════════════════════════════════════════════════╣"

INIT_PW=$(docker logs mailgo 2>/dev/null | grep -oP 'Web Login Password:\s+\K\S+' || echo "")
if [ -n "$INIT_PW" ]; then
  printf "║  Initial Password:  %-44s  ║\n" "$INIT_PW"
else
  printf "║  Check logs:  docker logs mailgo | grep Password                ║\n"
fi

echo "║                                                                  ║"
printf "║  Open:  http://localhost:%-40s  ║\n" "${SERVER_PORT:-8080}"
echo "║                                                                  ║"
echo "║  Reset password:  docker exec mailgo /app/mailgo -reset-password ║"
echo "║  Change password: Settings > Security > Change Password          ║"
echo "║                                                                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
